codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: 70..90

  status:
    # Global Project Coverage
    project:
      default:
        target: 80%     # The Gold Standard goal
        threshold: 1%   # Very strict - don't let it drop
        if_ci_failed: error
        informational: false
      
    # Patch Coverage (The "Ratchet")
    # Ensures new code is tested, preventing technical debt accumulation
    patch:
      default:
        target: 85%     # Realistic target for new code
        threshold: 5%   # Small leeway for boilerplate
        if_ci_failed: error
        informational: false

parsers:
  dotnet:
    # .NET 10/Coverage specific improvements if applicable
    # (Standard parsers usually suffice, keeping simple)

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - "tests/"
    carryforward: true

ignore:
  - "**/*.Designer.cs"
  - "**/*.g.cs"
  - "**/obj/**"
  - "**/bin/**"
  - "tests/**"
  - "tooling/**"
  - "docs/**"
  - "**/Program.cs"  # Often excluded from unit tests in microservices
  - "**/Startup.cs"